---
label: Template Blog
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: text
  name: author
  label: author
- type: list
  name: categories
  label: categories
- type: file
  name: image
  label: image
- type: text
  name: tags
  label: tags
pages:
- _posts/2019-12-09-mengenal-environment-php.md
